volumes:
  sockets:

networks:
  rinha:
    driver: bridge

services:
  haproxy:
    image: haproxy:3.3
    container_name: rinha-haproxy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/tmp/sockets
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

  api1:
    build: .
    environment:
      - PORT=8080
      - INSTANCE_ID=1
    volumes:
      - sockets:/tmp/sockets
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"

  api2:
    build: .
    environment:
      - PORT=8080
      - INSTANCE_ID=2
    volumes:
      - sockets:/tmp/sockets
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"
    